### ISSUE TITLE
Logo in docs.minio.io is pixelated.

### ISSUE THREAD

**Issue by deekoder** [MinioOps/doctor#10]
Please get it resolved.

**Comment by belvid** [comment]
Can you take a screenshot? Is looking good for me in my screen

**Comment by rushenn** [comment]
@belvid 
![logo-png](https://cloud.githubusercontent.com/assets/13393018/25050327/8234ea4a-2164-11e7-9cf7-d5be2079a18a.png)

**Comment by belvid** [comment]
@rushenn for me it looks like this (check screenshot). I cleared my cached files and is still looking good. Please note that is not showing the word DOCS. 
 
<img width="297" alt="screen shot 2017-04-14 at 4 33 49 pm" src="https://cloud.githubusercontent.com/assets/20955366/25058601/2c571aaa-2130-11e7-89b1-a86b30afa44b.png">


Also, when I go to inspect mode, I noticed that the natural size of the file is 137px x 218px, and when it gets resized it is 28px x 45px. So what I am going to do is I'll resize exactly to the logo to 28 x 45px and make that the natural size, just to see if it looks better on you screen. (check screenshot attached for reference).

<img width="510" alt="screen shot 2017-04-14 at 4 33 26 pm" src="https://cloud.githubusercontent.com/assets/20955366/25058602/31c13e62-2130-11e7-8b14-321d82fdc8a4.png">

**Comment by rushenn** [comment]
@belvid Logo get's pixelated only on low resolution screens. It looks good in my Macbook but not in my 24inch 1080p Monitor. The SVG logo you've given is perfect for any screens. 

FYI, if you use the exact resized dimension (28x45), it'll render properly on low resolution displays but not in retina displays.

**Comment by belvid** [comment]
I think we can close this now @deekoder.
